@startuml

left to right direction

actor "Nutzer:in" as stud
actor "Entwickler:in" as dev
actor "Logging" as log
actor "Benachrichtigungsdienst" as notif

package "Lost & Found System" {
  usecase "Verlustmeldung anonym aufgeben" as UC1
  usecase "Neue Fundmeldung anlegen" as UC2
  usecase "Informationen eingeben" as UC3
  usecase "Meldung speichern" as UC4
  usecase "Meldung veröffentlichen" as UC5
  usecase "Eingaben validieren (Client)" as UC6
  usecase "Eingaben validieren (Server)" as UC7
  usecase "Verständliche Fehlermeldung anzeigen" as UC8
  usecase "Exception abfangen & maskieren" as UC9
  usecase "Fehler protokollieren/alerten" as UC10
  usecase "Benachrichtigungspräferenzen setzen" as UC11
  usecase "Matching prüfen" as UC12
  usecase "Benachrichtigung generieren & senden" as UC13
  usecase "Benachrichtigung empfangen & interagieren" as UC14
}

stud --> UC1
stud --> UC2
stud --> UC11

UC1 --> UC3
UC2 --> UC3
UC3 --> UC6
UC6 --> UC7
UC7 --> UC4
UC4 --> UC5
UC5 --> UC12

UC12 --> UC13
UC13 --> notif
notif --> UC14
UC14 --> stud
UC7 --> UC8
UC7 --> UC9
UC9 --> UC10
UC10 --> log
UC10 --> dev

@enduml