@startuml

left to right direction

actor "Nutzer:in" as stud
actor "Entwickler:in" as dev
actor "Logging" as log
actor "Benachrichtigungsdienst" as notif

package "Lost & Found System" {
  usecase "Verlustmeldung anonym aufgeben" as UC1
  usecase "Neue Fundmeldung anlegen" as UC13
  usecase "Informationen eingeben" as UC2
  usecase "Meldung speichern" as UC6
  usecase "Meldung veröffentlichen" as UC7
  usecase "Eingaben validieren (Client)" as UC8
  usecase "Eingaben validieren (Server)" as UC9
  usecase "Verständliche Fehlermeldung anzeigen" as UC10
  usecase "Exception abfangen & maskieren" as UC11
  usecase "Fehler protokollieren/alerten" as UC12
  usecase "Benachrichtigungspräferenzen setzen" as UC14
  usecase "Matching prüfen" as UC15
  usecase "Benachrichtigung generieren & senden" as UC16
  usecase "Benachrichtigung empfangen & interagieren" as UC17
}

stud --> UC1
stud --> UC13
stud --> UC14

UC1 --> UC2
UC13 --> UC2
UC2 --> UC8
UC8 --> UC9
UC9 --> UC6
UC6 --> UC7
UC7 --> UC15

UC15 --> UC16
UC16 --> notif
notif --> UC17
UC17 --> stud
UC9 --> UC10
UC9 --> UC11
UC11 --> UC12
UC12 --> log
UC12 --> dev

@enduml